# **Análise de Dados COVID-19 - Brasil vs Canadá**

## Visão Geral
Este projeto realiza uma análise exploratória dos dados de COVID-19 no Brasil e Canadá, com o objetivo de identificar padrões, tendências e diferenças entre os países ao longo do tempo.

## Tecnologias Utilizadas

 - Python (Pandas)
 - Google Colab
 - Looker Studio (Dashboards)

# **COVID Dashboard**

## 1\. Introdução

### **1.1. A Pandemia Coronavírus 2019**

Em poucos meses, um vírus microscópico transformou o mundo, desafiando sistemas de saúde, economias e a vida moderna como nunca antes visto na história moderna, gerando uma grande pandemia que envolveu o mundo inteiro.

> A COVID-19 é uma infecção respiratória aguda causada pelo coronavírus SARS-CoV-2, potencialmente grave, de elevada transmissibilidade e de distribuição global.

Neste trabalho, iremos fazer uma análise visando construir um dashboard a fim de explorar dados e os visualizar interativamente sobre o avanço de casos e mortes causados pelo COVID-19 e também seu andamento com a vacinação no Brasil no ano de 2021 e entao compará-los com outro país. Usaremos o Canadá como comparação.

### **1.2. Dados, Fontes e Dashboards**

 - **Dashboards**:
  - Looker Studio: [Brasil](https://lookerstudio.google.com/reporting/a850f094-3193-4c9d-ac22-c5c01c4e610e) e [Canadá](https://lookerstudio.google.com/reporting/8ff57034-3d23-4c79-bd3e-a7a681bbcef0)
 - **Processamento**:
  - Github ([Link](https://github.com/ViniOF)).
  - Kaggle (`link`) (colocar)
 - **Fontes**:
  - Casos pela universidade John Hopkins ([Link](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports));
  - Vacinação pela universidade de Oxford ([Link](https://covid.ourworldindata.org/data/owid-covid-data.csv)).

Os dados sobre **casos da COVID-19** são compilados pelo centro de ciência de sistemas e engenharia da universidade americana **John Hopkins** ([link](https://www.jhu.edu)). Os dados são atualizados diariamente deste janeiro de 2020 com uma granularidade temporal de dias e geográfica de regiões de países (estados, condados, etc.). O website do projeto pode ser acessado neste [link](https://systems.jhu.edu/research/public-health/ncov/) enquanto os dados, neste [link](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports). Abaixo estão descritos os dados derivados do seu processamento.

 - **date**: data de referência;
 - **state**: estado;
 - **country**: país;
 - **population**: população estimada;
 - **confirmed**: número acumulado de infectados;
 - **confirmed_1d**: número diário de infectados;
 - **confirmed_moving_avg_7d**: média móvel de 7 dias do número diário de infectados;
 - **confirmed_moving_avg_7d_rate_14d**: média móvel de 7 dias dividido pela média móvel de 7 dias de 14 dias atrás;
 - **deaths**: número acumulado de mortos;
 - **deaths_1d**: número diário de mortos;
 - **deaths_moving_avg_7d**: média móvel de 7 dias do número diário de mortos;
 - **deaths_moving_avg_7d**: média móvel de 7 dias dividido pela média móvel de 7 dias de 14 dias atrás;
 - **month**: mês de referência;
 - **year**: ano de referência.

Os dados sobre **vacinação da COVID-19** são compilados pelo projeto Nosso Mundo em Dados (*Our World in Data* ou OWID) da universidade britânica de **Oxford** ([link](https://www.ox.ac.uk)). Os dados são **atualizados diariamente** deste janeiro de 2020 com uma **granularidade temporal de dias e geográfica de países**. O website do projeto pode ser acessado neste [link](https://ourworldindata.org) enquanto os dados, neste [link](https://covid.ourworldindata.org/data/owid-covid-data.csv). Abaixo estão descritos os dados derivados do seu processamento.

 - **date**: data de referência;
 - **country**: país;
 - **population**: população estimada;
 - **total**: número acumulado de doses administradas;
 - **one_shot**: número acumulado de pessoas com uma dose;
 - **one_shot_perc**: número acumulado relativo de pessoas com uma dose;
 - **two_shots**: número acumulado de pessoas com duas doses;
 - **two_shot_perc**: número acumulado relativo de pessoas com duas doses;
 - **three_shots**: número acumulado de pessoas com três doses;
 - **three_shot_perc**: número acumulado relativo de pessoas com três doses;
 - **month**: mês de referência;
 - **year**: ano de referência.

## 2\. Análise Exploratória de Dados

Nesta análise iremos usar o seguinte pacote de dados:

In [ ]:
import math
from typing import Iterator
from datetime import datetime, timedelta

import numpy as np
import pandas as pd

### **2\.1. Casos - Brasil**

Primeiramente, iremos processar os dados de **casos** da universidade de John Hopkins.

#### **2.1.1. Extração**

Os dados estão compilados em um arquivo por dia. Portanto, precisaremos extrair os dias necessários para a análise, que será o ano de 2021 inteiro.

E então selecionar as colunas de interesse e as linhas referentes ao Brasil, pois vamos trabalhar em cima apenas dos dados brasileiros.

In [ ]:
# Exemplo usando o dado de 01/12/2021.
cases = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-12-2021.csv', sep=',')

In [ ]:
cases.head(5000)

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-13 05:22:15,33.93911,67.709953,53584,2301,44608,6675,Afghanistan,137.647787,4.294192
1,NaN,NaN,NaN,Albania,2021-01-13 05:22:15,41.15330,20.168300,64627,1252,38421,24954,Albania,2245.708527,1.937271
2,NaN,NaN,NaN,Algeria,2021-01-13 05:22:15,28.03390,1.659600,102641,2816,69608,30217,Algeria,234.067409,2.743543
3,NaN,NaN,NaN,Andorra,2021-01-13 05:22:15,42.50630,1.521800,8682,86,7930,666,Andorra,11236.653077,0.990555
4,NaN,NaN,NaN,Angola,2021-01-13 05:22:15,-11.20270,17.873900,18343,422,15512,2409,Angola,55.811022,2.300605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-13 05:22:15,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-13 05:22:15,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-13 05:22:15,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-13 05:22:15,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-13 05:22:15,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

In [ ]:
def date_range(start_date: datetime, end_date: datetime) -> Iterator[datetime]:
  date_range_days: int = (end_date - start_date).days
  for lag in range(date_range_days + 1):
    yield start_date + timedelta(lag)

In [ ]:
start_date = datetime(2021,  1,  1)
end_date   = datetime(2021, 12, 31)

In [ ]:
cases = None
cases_is_empty = True

for date in date_range(start_date=start_date, end_date=end_date):

  date_str = date.strftime('%m-%d-%Y')
  data_source_url = f'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/{date_str}.csv'

  case = pd.read_csv(data_source_url, sep=',')

  case = case.drop(['FIPS', 'Admin2', 'Last_Update', 'Lat', 'Long_', 'Recovered', 'Active', 'Combined_Key', 'Case_Fatality_Ratio'], axis=1)
  case = case.query('Country_Region == "Brazil"').reset_index(drop=True)
  case['Date'] = pd.to_datetime(date.strftime('%Y-%m-%d'))
  if cases_is_empty:
    cases = case
    cases_is_empty = False
  else:
    cases = pd.concat([cases, case], axis= 0, ignore_index=True)

#### **2.1.2. Wrangling**

Aqui, faremos o ajuste dos dados para que fique melhor apresentável.

In [ ]:
cases.head()

  Province_State Country_Region  Confirmed  Deaths  Incident_Rate       Date
0           Acre         Brazil      41689     796    4726.992352 2021-01-01
1        Alagoas         Brazil     105091    2496    3148.928928 2021-01-01
2          Amapa         Brazil      68361     926    8083.066602 2021-01-01
3       Amazonas         Brazil     201574    5295    4863.536793 2021-01-01
4          Bahia         Brazil     494684    9159    3326.039611 2021-01-01

In [ ]:
cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9855 entries, 0 to 9854
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province_State  9855 non-null   object
 1   Country_Region  9855 non-null   object
 2   Confirmed       9855 non-null   int64
 3   Deaths          9855 non-null   int64
 4   Incident_Rate   9855 non-null   float64
 5   Date            9855 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 462.1+ KB

Vamos começar ajustando o nome das colunas, e logo a seguir, o nome dos estados.

In [ ]:
cases = cases.rename(
  columns={
    'Province_State': 'state',
    'Country_Region': 'country'
  }
)

for col in cases.columns:
  cases = cases.rename(columns={col: col.lower()})

In [ ]:
states_map = {
    'Amapa': 'Amapá',
    'Ceara': 'Ceará',
    'Espirito Santo': 'Espírito Santo',
    'Goias': 'Goiás',
    'Para': 'Pará',
    'Paraiba': 'Paraíba',
    'Parana': 'Paraná',
    'Piaui': 'Piauí',
    'Rondonia': 'Rondônia',
    'Sao Paulo': 'São Paulo'
}

cases['state'] = cases['state'].apply(lambda state: states_map.get(state) if state in states_map.keys() else state)

In [ ]:
cases.head()

      state country  confirmed  deaths  incident_rate       date
0      Acre  Brazil      41689     796    4726.992352 2021-01-01
1   Alagoas  Brazil     105091    2496    3148.928928 2021-01-01
2     Amapá  Brazil      68361     926    8083.066602 2021-01-01
3  Amazonas  Brazil     201574    5295    4863.536793 2021-01-01
4     Bahia  Brazil     494684    9159    3326.039611 2021-01-01

A seguir, adicionaremos mais algumas colunas a fim de enriquecer nossa base de dados.

 - Chaves temporais:

In [ ]:
cases['month'] = cases['date'].apply(lambda date: date.strftime('%m'))
cases['year']  = cases['date'].apply(lambda date: date.strftime('%Y'))

 - População estimada do estado:

In [ ]:
cases['population'] = round(100000 * (cases['confirmed'] / cases['incident_rate']))
cases = cases.drop('incident_rate', axis=1)

- Número, média móvel (7 dias) e estabilidade (14 dias) de casos confirmados e mortes por estado:

In [ ]:
cases_ = None
cases_is_empty = True

def get_trend(rate: float) -> str:

  if np.isnan(rate):
    return np.nan

  if rate < 0.75:    # Se a divisão for menor que 0.75 (correção 0.85)
    status = 'downward'
  elif rate > 1.15:
    status = 'upward'
  else:
    status = 'stable'

  return status


for state in cases['state'].drop_duplicates():

  cases_per_state = cases.query(f'state == "{state}"').reset_index(drop=True)
  cases_per_state = cases_per_state.sort_values(by=['date'])

  cases_per_state['confirmed_1d'] = cases_per_state['confirmed'].diff(periods=1)
  cases_per_state['confirmed_moving_avg_7d'] = np.ceil(cases_per_state['confirmed_1d'].rolling(window=7).mean())
  cases_per_state['confirmed_moving_avg_7d_rate_14d'] = cases_per_state['confirmed_moving_avg_7d']/cases_per_state['confirmed_moving_avg_7d'].shift(periods=14)
  cases_per_state['confirmed_trend'] = cases_per_state['confirmed_moving_avg_7d_rate_14d'].apply(get_trend)

  cases_per_state['deaths_1d'] = cases_per_state['deaths'].diff(periods=1)
  cases_per_state['deaths_moving_avg_7d'] = np.ceil(cases_per_state['deaths_1d'].rolling(window=7).mean())
  cases_per_state['deaths_moving_avg_7d_rate_14d'] = cases_per_state['deaths_moving_avg_7d']/cases_per_state['deaths_moving_avg_7d'].shift(periods=14)
  cases_per_state['deaths_trend'] = cases_per_state['deaths_moving_avg_7d_rate_14d'].apply(get_trend)

  if cases_is_empty:
    cases_ = cases_per_state
    cases_is_empty = False
  else:
    cases_ = pd.concat([cases_, cases_per_state],axis=0, ignore_index=True)

cases = cases_
cases_ = None

E então, faremos o *type casting* das colunas, garantindo assim, uma base mais sólida dos dados.

In [ ]:
cases['population'] = cases['population'].astype('Int64')
cases['confirmed_1d'] = cases['confirmed_1d'].astype('Int64')
cases['confirmed_moving_avg_7d'] = cases['confirmed_moving_avg_7d'].astype('Int64')
cases['deaths_1d'] = cases['deaths_1d'].astype('Int64')
cases['deaths_moving_avg_7d'] = cases['deaths_moving_avg_7d'].astype('Int64')

Por fim, reorganizaremos as colunas com o intuito de ficar melhor apresentável.

In [ ]:
cases = cases[['date', 'country', 'state', 'population', 'confirmed', 'confirmed_1d', 'confirmed_moving_avg_7d', 'confirmed_moving_avg_7d_rate_14d', 'confirmed_trend', 'deaths', 'deaths_1d', 'deaths_moving_avg_7d', 'deaths_moving_avg_7d_rate_14d', 'deaths_trend', 'month', 'year']]

In [ ]:
cases.head()

,date,country,state,population,confirmed,confirmed_1d,confirmed_moving_avg_7d,confirmed_moving_avg_7d_rate_14d,confirmed_trend,deaths,deaths_1d,deaths_moving_avg_7d,deaths_moving_avg_7d_rate_14d,deaths_trend,month,year
0,2021-01-01,Brazil,Acre,881935,41689,<NA>,<NA>,NaN,NaN,796,<NA>,<NA>,NaN,NaN,01,2021
1,2021-01-02,Brazil,Acre,881935,41941,252,<NA>,NaN,NaN,798,2,<NA>,NaN,NaN,01,2021
2,2021-01-03,Brazil,Acre,881935,42046,105,<NA>,NaN,NaN,802,4,<NA>,NaN,NaN,01,2021
3,2021-01-04,Brazil,Acre,881935,42117,71,<NA>,NaN,NaN,806,4,<NA>,NaN,NaN,01,2021
4,2021-01-05,Brazil,Acre,881935,42170,53,<NA>,NaN,NaN,808,2,<NA>,NaN,NaN,01,2021

In [ ]:
cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9855 entries, 0 to 9854
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   date                              9855 non-null   datetime64[ns]
 1   country                           9855 non-null   object
 2   state                             9855 non-null   object
 3   population                        9855 non-null   Int64
 4   confirmed                         9855 non-null   int64
 5   confirmed_1d                      9828 non-null   Int64
 6   confirmed_moving_avg_7d           9666 non-null   Int64
 7   confirmed_moving_avg_7d_rate_14d  9288 non-null   float64
 8   confirmed_trend                   9288 non-null   object
 9   deaths                            9855 non-null   int64
 10  deaths_1d                         9828 non-null   Int64
 11  deaths_moving_avg_7d              9666 non-null   Int64
 12  deaths_moving_avg_7d_rate_14d     9271 non-null   float64
 13  deaths_trend                      9271 non-null   object
 14  month                             9855 non-null   object
 15  year                              9855 non-null   object
dtypes: Int64(5), datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 1.3+ MB

#### **2.1.3. Carregamento**

In [ ]:
cases.to_csv('./covid-cases.csv', sep=',', index=False)

Com os dados prontos, iremos importá-lo para csv e faremos o carregamento no Looker Studio.

### **2.2. Vacinação - Brasil**

Agora, processaremos os dados de vacinação da Universidade de Oxford.

#### **2.2.1. Extração**

Diferente dos dados de Casos, os dados da vacinação estão em um único arquivo.

In [ ]:
vaccines = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv', sep=',', parse_dates=[3])

In [ ]:
vaccines.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN

Então, selecionaremos as colunas de interesse e as linhas referentes ao Brasil.

In [ ]:
vaccines = vaccines.query('location == "Brazil"').reset_index(drop=True)
vaccines = vaccines[['location', 'population', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 'date']]

#### **2.2.2. Wrangling**

Agora manipularemos os dados para o Dashboard. Garantindo assim, uma boa granularidade da base de dados.

In [ ]:
vaccines.head()

,location,population,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,date
0,Brazil,215313504,NaN,NaN,NaN,NaN,2020-01-05
1,Brazil,215313504,NaN,NaN,NaN,NaN,2020-01-06
2,Brazil,215313504,NaN,NaN,NaN,NaN,2020-01-07
3,Brazil,215313504,NaN,NaN,NaN,NaN,2020-01-08
4,Brazil,215313504,NaN,NaN,NaN,NaN,2020-01-09

In [ ]:
vaccines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1674 entries, 0 to 1673
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   location                 1674 non-null   object
 1   population               1674 non-null   int64
 2   total_vaccinations       695 non-null    float64
 3   people_vaccinated        691 non-null    float64
 4   people_fully_vaccinated  675 non-null    float64
 5   total_boosters           455 non-null    float64
 6   date                     1674 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 91.7+ KB

Primeiramente, tratando dados faltantes.

In [ ]:
vaccines = vaccines.ffill()

E então, filtraremos os dados para que sejam a mesma data contida nos casos, e alteraremos o nome das colunas.

In [ ]:
vaccines = vaccines[(vaccines['date'] >= '2021-01-01') & (vaccines['date'] <= '2021-12-31')].reset_index(drop=True)

In [ ]:
vaccines = vaccines.rename(
  columns={
    'location': 'country',
    'total_vaccinations': 'total',
    'people_vaccinated': 'one_shot',
    'people_fully_vaccinated': 'two_shots',
    'total_boosters': 'three_shots',
  }
)

Logo após, adicionaremos mais algumas informações a fim de enriquecer a base de dados, assim como nos Casos.

 - Chaves Temporais:

In [ ]:
vaccines['month'] = vaccines['date'].apply(lambda date: date.strftime('%m'))
vaccines['year']  = vaccines['date'].apply(lambda date: date.strftime('%Y'))

 - Dados relativos:

In [ ]:
vaccines['one_shot_perc'] = round(vaccines['one_shot'] / vaccines['population'], 4)
vaccines['two_shots_perc'] = round(vaccines['two_shots'] / vaccines['population'], 4)
vaccines['three_shots_perc'] = round(vaccines['three_shots'] / vaccines['population'], 4)

Por fim, garantiremos que o tipo de dado seja o correto, fazendo um *type casting* das colunas, e então as reorganizaremos.

In [ ]:
vaccines['population'] = vaccines['population'].astype('Int64')
vaccines['total'] = vaccines['total'].astype('Int64')
vaccines['one_shot'] = vaccines['one_shot'].astype('Int64')
vaccines['two_shots'] = vaccines['two_shots'].astype('Int64')
vaccines['three_shots'] = vaccines['three_shots'].astype('Int64')

vaccines = vaccines[['date', 'country', 'population', 'total', 'one_shot', 'one_shot_perc', 'two_shots', 'two_shots_perc', 'three_shots', 'three_shots_perc', 'month', 'year']]

In [ ]:
vaccines.tail()

,date,country,population,total,one_shot,one_shot_perc,two_shots,two_shots_perc,three_shots,three_shots_perc,month,year
360,2021-12-27,Brazil,215313504,329011365,165952037,0.7707,142764283,0.6631,25218893,0.1171,12,2021
361,2021-12-28,Brazil,215313504,329861730,166062249,0.7713,142965728,0.6640,25758909,0.1196,12,2021
362,2021-12-29,Brazil,215313504,330718457,166143380,0.7716,143282084,0.6655,26219623,0.1218,12,2021
363,2021-12-30,Brazil,215313504,331164041,166185628,0.7718,143398692,0.6660,26507937,0.1231,12,2021
364,2021-12-31,Brazil,215313504,331273910,166195505,0.7719,143436012,0.6662,26571077,0.1234,12,2021

#### **2.2.3. Carregamento**

E assim como nos Casos, importaremos o csv, e carregaremos no Looker Studio.

In [ ]:
vaccines.to_csv('./covid-vaccines.csv', sep=',', index=False)

### 2.3. Casos - Canada

#### **2.3.1. Extração**

Por fim, repetiremos o mesmo processo realizado no Brasil, no Canadá, visando analisar os casos e as vacinações também.

In [ ]:
cases = None
cases_is_empty = True

for date in date_range(start_date=start_date, end_date=end_date):

  date_str = date.strftime('%m-%d-%Y')
  data_source_url = f'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/{date_str}.csv'

  case = pd.read_csv(data_source_url, sep=',')

  case = case.drop(['FIPS', 'Admin2', 'Last_Update', 'Lat', 'Long_', 'Recovered', 'Active', 'Combined_Key', 'Case_Fatality_Ratio'], axis=1)
  case = case.query('Country_Region == "Canada"').reset_index(drop=True)
  case['Date'] = pd.to_datetime(date.strftime('%Y-%m-%d'))
  if cases_is_empty:
    cases = case
    cases_is_empty = False
  else:
    cases = pd.concat([cases, case], axis= 0, ignore_index=True)

#### **2.3.2. Wrangling**

Apenas um adendo, iremos remover os casos presentes em Grand Princess, Diamond Princess e Repatriated Travellers, devido a não serem tão importante para a análise.

In [ ]:
cases_filtered = cases[~cases['Province_State'].isin(['Grand Princess', 'Diamond Princess', 'Repatriated Travellers'])]
cases = cases_filtered.reset_index(drop=True)

In [ ]:
cases.head()

,Province_State,Country_Region,Confirmed,Deaths,Incident_Rate,Date
0,Alberta,Canada,100428,1046,2260.426179,2021-01-01
1,British Columbia,Canada,51990,901,996.969206,2021-01-01
2,Manitoba,Canada,24700,667,1784.985167,2021-01-01
3,New Brunswick,Canada,601,9,76.150654,2021-01-01
4,Newfoundland and Labrador,Canada,390,4,74.920325,2021-01-01

In [ ]:
cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4745 entries, 0 to 4744
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province_State  4745 non-null   object
 1   Country_Region  4745 non-null   object
 2   Confirmed       4745 non-null   int64
 3   Deaths          4745 non-null   int64
 4   Incident_Rate   4745 non-null   float64
 5   Date            4745 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 222.6+ KB

In [ ]:
cases = cases.rename(
  columns={
    'Province_State': 'state',
    'Country_Region': 'country'
  }
)

for col in cases.columns:
  cases = cases.rename(columns={col: col.lower()})

In [ ]:
cases.head()

,state,country,confirmed,deaths,incident_rate,date
0,Alberta,Canada,100428,1046,2260.426179,2021-01-01
1,British Columbia,Canada,51990,901,996.969206,2021-01-01
2,Manitoba,Canada,24700,667,1784.985167,2021-01-01
3,New Brunswick,Canada,601,9,76.150654,2021-01-01
4,Newfoundland and Labrador,Canada,390,4,74.920325,2021-01-01

In [ ]:
cases['month'] = cases['date'].apply(lambda date: date.strftime('%m'))
cases['year']  = cases['date'].apply(lambda date: date.strftime('%Y'))

In [ ]:
cases['population'] = round(100000 * (cases['confirmed'] / cases['incident_rate']))
cases = cases.drop('incident_rate', axis=1)

In [ ]:
cases_ = None
cases_is_empty = True

def get_trend(rate: float) -> str:

  if np.isnan(rate):
    return np.nan

  if rate < 0.75:    # Se a divisão for menor que 0.75 (correção 0.85)
    status = 'downward'
  elif rate > 1.15:
    status = 'upward'
  else:
    status = 'stable'

  return status


for state in cases['state'].drop_duplicates():

  cases_per_state = cases.query(f'state == "{state}"').reset_index(drop=True)
  cases_per_state = cases_per_state.sort_values(by=['date'])

  cases_per_state['confirmed_1d'] = cases_per_state['confirmed'].diff(periods=1)
  cases_per_state['confirmed_moving_avg_7d'] = np.ceil(cases_per_state['confirmed_1d'].rolling(window=7).mean())
  cases_per_state['confirmed_moving_avg_7d_rate_14d'] = cases_per_state['confirmed_moving_avg_7d']/cases_per_state['confirmed_moving_avg_7d'].shift(periods=14)
  cases_per_state['confirmed_trend'] = cases_per_state['confirmed_moving_avg_7d_rate_14d'].apply(get_trend)

  cases_per_state['deaths_1d'] = cases_per_state['deaths'].diff(periods=1)
  cases_per_state['deaths_moving_avg_7d'] = np.ceil(cases_per_state['deaths_1d'].rolling(window=7).mean())
  cases_per_state['deaths_moving_avg_7d_rate_14d'] = cases_per_state['deaths_moving_avg_7d']/cases_per_state['deaths_moving_avg_7d'].shift(periods=14)
  cases_per_state['deaths_trend'] = cases_per_state['deaths_moving_avg_7d_rate_14d'].apply(get_trend)

  if cases_is_empty:
    cases_ = cases_per_state
    cases_is_empty = False
  else:
    cases_ = pd.concat([cases_, cases_per_state],axis=0, ignore_index=True)

cases = cases_
cases_ = None

In [ ]:
cases['population'] = cases['population'].astype('Int64')
cases['confirmed_1d'] = cases['confirmed_1d'].astype('Int64')
cases['confirmed_moving_avg_7d'] = cases['confirmed_moving_avg_7d'].astype('Int64')
cases['deaths_1d'] = cases['deaths_1d'].astype('Int64')
cases['deaths_moving_avg_7d'] = cases['deaths_moving_avg_7d'].astype('Int64')

In [ ]:
cases = cases[['date', 'country', 'state', 'population', 'confirmed', 'confirmed_1d', 'confirmed_moving_avg_7d', 'confirmed_moving_avg_7d_rate_14d', 'confirmed_trend', 'deaths', 'deaths_1d', 'deaths_moving_avg_7d', 'deaths_moving_avg_7d_rate_14d', 'deaths_trend', 'month', 'year']]

In [ ]:
cases.head()

,date,country,state,population,confirmed,confirmed_1d,confirmed_moving_avg_7d,confirmed_moving_avg_7d_rate_14d,confirmed_trend,deaths,deaths_1d,deaths_moving_avg_7d,deaths_moving_avg_7d_rate_14d,deaths_trend,month,year
0,2021-01-01,Canada,Alberta,4442879,100428,<NA>,<NA>,NaN,NaN,1046,<NA>,<NA>,NaN,NaN,01,2021
1,2021-01-02,Canada,Alberta,4442879,100428,0,<NA>,NaN,NaN,1046,0,<NA>,NaN,NaN,01,2021
2,2021-01-03,Canada,Alberta,4442879,104228,3800,<NA>,NaN,NaN,1046,0,<NA>,NaN,NaN,01,2021
3,2021-01-04,Canada,Alberta,4442879,105535,1307,<NA>,NaN,NaN,1142,96,<NA>,NaN,NaN,01,2021
4,2021-01-05,Canada,Alberta,4442879,106378,843,<NA>,NaN,NaN,1168,26,<NA>,NaN,NaN,01,2021

In [ ]:
cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4745 entries, 0 to 4744
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   date                              4745 non-null   datetime64[ns]
 1   country                           4745 non-null   object
 2   state                             4745 non-null   object
 3   population                        4745 non-null   Int64
 4   confirmed                         4745 non-null   int64
 5   confirmed_1d                      4732 non-null   Int64
 6   confirmed_moving_avg_7d           4654 non-null   Int64
 7   confirmed_moving_avg_7d_rate_14d  4235 non-null   float64
 8   confirmed_trend                   4235 non-null   object
 9   deaths                            4745 non-null   int64
 10  deaths_1d                         4732 non-null   Int64
 11  deaths_moving_avg_7d              4654 non-null   Int64
 12  deaths_moving_avg_7d_rate_14d     2885 non-null   float64
 13  deaths_trend                      2885 non-null   object
 14  month                             4745 non-null   object
 15  year                              4745 non-null   object
dtypes: Int64(5), datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 616.4+ KB

#### 2.3.3. Carregamento

In [ ]:
cases.to_csv('./covid-cases-canada.csv', sep=',', index=False)

### 2.4. Vacinação - Canada

#### 2.4.1. Extração

In [ ]:
vaccines = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv', sep=',', parse_dates=[3])

In [ ]:
vaccines.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN

In [ ]:
vaccines = vaccines.query('location == "Canada"').reset_index(drop=True)
vaccines = vaccines[['location', 'population', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 'date']]

#### 2.4.2. Wrangling

In [ ]:
vaccines.head()

,location,population,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,date
0,Canada,38454328,NaN,NaN,NaN,NaN,2020-01-05
1,Canada,38454328,NaN,NaN,NaN,NaN,2020-01-06
2,Canada,38454328,NaN,NaN,NaN,NaN,2020-01-07
3,Canada,38454328,NaN,NaN,NaN,NaN,2020-01-08
4,Canada,38454328,NaN,NaN,NaN,NaN,2020-01-09

In [ ]:
vaccines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1674 entries, 0 to 1673
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   location                 1674 non-null   object
 1   population               1674 non-null   int64
 2   total_vaccinations       1264 non-null   float64
 3   people_vaccinated        701 non-null    float64
 4   people_fully_vaccinated  745 non-null    float64
 5   total_boosters           1204 non-null   float64
 6   date                     1674 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 91.7+ KB

In [ ]:
vaccines = vaccines.ffill()

In [ ]:
vaccines = vaccines[(vaccines['date'] >= '2021-01-01') & (vaccines['date'] <= '2021-12-31')].reset_index(drop=True)

In [ ]:
vaccines = vaccines.rename(
  columns={
    'location': 'country',
    'total_vaccinations': 'total',
    'people_vaccinated': 'one_shot',
    'people_fully_vaccinated': 'two_shots',
    'total_boosters': 'three_shots',
  }
)

In [ ]:
vaccines['month'] = vaccines['date'].apply(lambda date: date.strftime('%m'))
vaccines['year']  = vaccines['date'].apply(lambda date: date.strftime('%Y'))

In [ ]:
vaccines['one_shot_perc'] = round(vaccines['one_shot'] / vaccines['population'], 4)
vaccines['two_shots_perc'] = round(vaccines['two_shots'] / vaccines['population'], 4)
vaccines['three_shots_perc'] = round(vaccines['three_shots'] / vaccines['population'], 4)

In [ ]:
vaccines['population'] = vaccines['population'].astype('Int64')
vaccines['total'] = vaccines['total'].astype('Int64')
vaccines['one_shot'] = vaccines['one_shot'].astype('Int64')
vaccines['two_shots'] = vaccines['two_shots'].astype('Int64')
vaccines['three_shots'] = vaccines['three_shots'].astype('Int64')

vaccines = vaccines[['date', 'country', 'population', 'total', 'one_shot', 'one_shot_perc', 'two_shots', 'two_shots_perc', 'three_shots', 'three_shots_perc', 'month', 'year']]

In [ ]:
vaccines.tail()

,date,country,population,total,one_shot,one_shot_perc,two_shots,two_shots_perc,three_shots,three_shots_perc,month,year
360,2021-12-27,Canada,38454328,67366693,31652630,0.8231,29392851,0.7644,6321212,0.1644,12,2021
361,2021-12-28,Canada,38454328,67651591,31665961,0.8235,29401905,0.7646,6583725,0.1712,12,2021
362,2021-12-29,Canada,38454328,68167603,31705383,0.8245,29415414,0.7649,7046806,0.1833,12,2021
363,2021-12-30,Canada,38454328,68508996,31725902,0.8250,29426006,0.7652,7357088,0.1913,12,2021
364,2021-12-31,Canada,38454328,68836546,31746146,0.8256,29437317,0.7655,7653083,0.1990,12,2021

#### 2.4.3. Carregamento

In [ ]:
vaccines.to_csv('./covid-vaccines-canada.csv', sep=',', index=False)

## **3\. Exploração Interativa de Dados**

Os dados estarão presentes nestes links:
[Brasil](https://lookerstudio.google.com/reporting/a850f094-3193-4c9d-ac22-c5c01c4e610e) e [Canadá](https://lookerstudio.google.com/reporting/8ff57034-3d23-4c79-bd3e-a7a681bbcef0)

### **3.1. KPIs**

O dashboard de dados contem os seguintes indicadores chaves de desempenho (*key performance indicator* ou KPI) consolidados:

1. Casos e mortes nas 24 horas;
1. Média móvel (7 dias) de casos e mortes;
1. Tendência de casos e mortes;
1. Proporção de vacinados com 1ª, 2ª e 3ª doses.

### **3.2. EDA**

O dashboard de dados contem os seguintes gráficos para a análise exploratória de dados (*exploratory data analysis*
ou EDA) interativa:

1. Distribuição do números de casos e mortes ao longo do tempo;
1. Distribuição da média móvel (7 dias) do números de casos e mortes ao longo do tempo;
1. Distribuição geográfica dos casos por estado por dia.

## **4\. Conclusão**

Comparando os dois gráficos, podemos observar diferenças significativas entre o Brasil e o Canadá ao longo do ano de 2021.

O Brasil teve os números mais inflados que o Canadá em todos os aspectos. Até o mês de Junho, o número de casos no Brasil foi extremamente alto, então decaindo lentamente, demonstrando uma melhora no controle dos casos obtidos. Por outro lado, no Canadá, o número de casos ao longo do ano foram bem mais controlados, com uma explosão intensa no final do ano, provavelmente devido a variante Ômicron.

Ao longo do ano, o Brasil teve, também, um número de mortes muito maior que o Canadá, entretanto seu pico de mortes fora diferente em cada país, o Brasil sendo mais ou menos em abril e no Canadá no começo do ano. E, é claro, a curva de mortes decaiu mais rapidamente no Canadá, demonstrando assim, um melhor controle de danos e eficácia nas medidas de mitigação.

O Brasil por um lado, enfrentou maiores dificuldades em relação a pandemia ao longo do ano, provavelmente devido a medidas de contenção menos rígidas, ausência de responsabilidade de muitas pessoas e dificuldade em estruturas que o país passa, transporte público lotados, entre outros. Também se da por, provavelmente, muitas pessoas precisarem sair de casa para conseguir botar comida na mesa no fim do dia, não havendo a possibilidade de trabalhar remotamente.

Por outro lado, o Canadá, passou por menos dificuldades que o Brasil, conseguindo manter todos os números controlados, tanto de casos, quanto de mortes e vacinação. Apesar de seu grande pico no final do ano, as vacinações conseguiram mitigar bem a situação, mantendo um número de mortes mais baixa.

Por fim, devemos levar em consideração todas as festas em datas comemorativas, como Natal e Ano novo e a variante Ômicron.

Logo, podemos concluir que o Brasil passou por muito mais dificuldades que o Canadá ao longo de 2021, especialmente no primeiro semestre. O Canadá no geral, conseguiu manter os números mais controlados que o Brasil, apesar da explosão no fim do ano. Sugerindo assim que políticas de saúde pública, medidas de contenção e vacinação, desempenharam um papel crucial no impacto da pandemia de cada país, porém, com a falta de estrutura, medidas de contenção menos rígidas e pessoas irresponsáveis, o Brasil teve, infelizmente, uma taxa de casos e mortes muito maiores.

## Observação

Este projeto foi desenvolvido como parte de um exercício prático do curso de Análise de Dados da EBAC, sendo adaptado e estruturado de forma independente para fins de portfólio.